sections:
  main:
    display: Main
    fields:
      -
        handle: logo
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Logo
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: title
        field:
          input_type: text
          antlers: false
          display: Title
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
      -
        handle: intro
        field:
          input_type: text
          antlers: false
          display: Intro
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: description
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: Description
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  work:
    display: Work
    fields:
      -
        handle: work_url
        field:
          display: 'Work URL'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: work_place
        field:
          input_type: text
          antlers: false
          display: 'Work Place'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
      -
        handle: work_title
        field:
          input_type: text
          antlers: false
          display: 'Work Title'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
      -
        handle: work_description
        field:
          antlers: false
          display: 'Work Description'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
  socials:
    display: Socials
    fields:
      -
        handle: linkedin
        field:
          display: LinkedIn
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
      -
        handle: github
        field:
          display: GitHub
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
      -
        handle: twitter
        field:
          display: Twitter
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
      -
        handle: telegram
        field:
          display: Telegram
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
