sections:
  main:
    display: Main
    fields:
      -
        handle: image
        field:
          mode: list
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          instructions: 'A small image, or logo relating to the project'
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: description
        field:
          input_type: text
          antlers: false
          display: Description
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: project_url
        field:
          display: URL
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: website
        field:
          input_type: text
          antlers: false
          display: Website
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: order
        field:
          display: Order
          type: integer
          icon: integer
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: date
        field:
          type: date
          validate:
            - required
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: Project
