sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
            - string
          display: name
          instructions_position: above
          listable: hidden
          visibility: visible
          always_save: false
          input_type: text
          antlers: false
      -
        handle: description
        field:
          input_type: text
          character_limit: 90
          antlers: false
          display: description
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
            - string
            - 'max:90'
      -
        handle: github_link
        field:
          display: 'GitHub Link'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
            - active_url
title: Project
