name: CI

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Code Style
        run: ./vendor/bin/pint --test

      - name: Deploy
        if: github.ref_name == 'main'
        run: curl ${{ secrets.DEPLOY_HOOK }}?sha=${{ github.sha }}
